DOTCLOUD_ENVIRONMENT: default
DOTCLOUD_NOSQLDB_REDIS_HOST: whatever-polettix.dotcloud.com
DOTCLOUD_NOSQLDB_REDIS_LOGIN: redis
DOTCLOUD_NOSQLDB_REDIS_PASSWORD: redis-password-here
DOTCLOUD_NOSQLDB_REDIS_PORT: '13749'
DOTCLOUD_NOSQLDB_REDIS_URL: redis://redis:redis-password-here@whatever-polettix.dotcloud.com:13749
DOTCLOUD_PROJECT: whatever
DOTCLOUD_SERVICE_ID: 0
DOTCLOUD_SERVICE_NAME: www
DOTCLOUD_SQLDB_MYSQL_HOST: whatever-polettix.dotcloud.com
DOTCLOUD_SQLDB_MYSQL_LOGIN: root
DOTCLOUD_SQLDB_MYSQL_PASSWORD: mysql-password-here
DOTCLOUD_SQLDB_MYSQL_PORT: '13747'
DOTCLOUD_SQLDB_MYSQL_URL: mysql://root:mysql-password-here@whatever-polettix.dotcloud.com:13747
